[workspace]

members = [
    "lesson3",
    "lesson9",
    "lesson17",
    "lesson19",
    "lesson25",
    "lesson27",
    "lesson30",
    "lesson34",
    "lesson37",
    "lesson38",
    "lesson40",
    "tokio-example-redis"
]

resolver = "2"
