[package]
name = "lesson34"
version = "0.1.0"
edition = "2021"

[lib]
name = "common"         # The name of the target.
path = "src/lib/lib.rs"

[[bin]]
name = "server"
path = "src/server/server.rs"

[[bin]]
name = "client"
path = "src/client/client.rs"

[dependencies]
