[package]
name = "lesson37"
version = "0.1.0"
edition = "2021"

[lib]
name = "common"         # The name of the target.
path = "src/lib/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "1.3" }
log = "0.4"
ftail = "0.2"
