[package]
name = "tokio-example-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
# thiserror = { version = "2.0" }
# anyhow = "1.0"
